#ifndef TOKEN_H
#define TOKEN_H

class Token {
    public: 
        Token();
};

enum TokenType {
    // Grouping / brackets
    TOKEN_LEFT_PAREN, TOKEN_RIGHT_PAREN,
    TOKEN_LEFT_BRACE, TOKEN_RIGHT_BRACE,
    TOKEN_LEFT_BRACKET, TOKEN_RIGHT_BRACKET,

    // Separators / misc punctuation
    TOKEN_SEMICOLON, TOKEN_COMMA, TOKEN_COLON, TOKEN_QUESTION,
    TOKEN_DOT, TOKEN_ARROW, TOKEN_ELLIPSIS,          // .  ->  ...

    // Arithmetic
    TOKEN_PLUS, TOKEN_MINUS, TOKEN_STAR, TOKEN_SLASH, TOKEN_PERCENT,

    // Increment / decrement
    TOKEN_PLUS_PLUS, TOKEN_MINUS_MINUS,

    // Bitwise
    TOKEN_AMP, TOKEN_PIPE, TOKEN_CARET, TOKEN_TILDE,
    TOKEN_LSHIFT, TOKEN_RSHIFT,                       // <<  >>

    // Logical
    TOKEN_AMP_AMP, TOKEN_PIPE_PIPE, TOKEN_BANG,       // &&  ||  !

    // Comparison
    TOKEN_LESS, TOKEN_LESS_EQUAL,
    TOKEN_GREATER, TOKEN_GREATER_EQUAL,
    TOKEN_EQUAL_EQUAL, TOKEN_BANG_EQUAL,             // ==  !=

    // Assignment
    TOKEN_EQUAL,
    TOKEN_PLUS_EQUAL, TOKEN_MINUS_EQUAL,
    TOKEN_STAR_EQUAL, TOKEN_SLASH_EQUAL, TOKEN_PERCENT_EQUAL,
    TOKEN_AMP_EQUAL, TOKEN_PIPE_EQUAL, TOKEN_CARET_EQUAL,
    TOKEN_LSHIFT_EQUAL, TOKEN_RSHIFT_EQUAL,           // <<=  >>=

    // Literals 
    TOKEN_IDENTIFIER,
    TOKEN_INT_LIT, TOKEN_FLOAT_LIT,
    TOKEN_CHAR_LIT, TOKEN_STRING_LIT,                 // 'a'  "hello"

    // Keywords (C89 — 32)
    TOKEN_AUTO, TOKEN_BREAK, TOKEN_CASE, TOKEN_CHAR, TOKEN_CONST,
    TOKEN_CONTINUE, TOKEN_DEFAULT, TOKEN_DO, TOKEN_DOUBLE, TOKEN_ELSE,
    TOKEN_ENUM, TOKEN_EXTERN, TOKEN_FLOAT, TOKEN_FOR, TOKEN_GOTO,
    TOKEN_IF, TOKEN_INT, TOKEN_LONG, TOKEN_REGISTER, TOKEN_RETURN,
    TOKEN_SHORT, TOKEN_SIGNED, TOKEN_SIZEOF, TOKEN_STATIC, TOKEN_STRUCT,
    TOKEN_SWITCH, TOKEN_TYPEDEF, TOKEN_UNION, TOKEN_UNSIGNED, TOKEN_VOID,
    TOKEN_VOLATILE, TOKEN_WHILE,

    TOKEN_EOF
};

#endif
